apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
- application.yaml
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: my-app