apiVersion: v1
kind: Service
metadata:
  name: whatsapp-frontend-service
spec:
  selector:
    app: whatsapp-frontend
  ports:
  - port: 80
    targetPort: 3000  # ← Match your app's port
  type: ClusterIP