apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: whatsapp-frontend
        # Development-specific settings
        command: ["npm"]
        args: ["run", "dev"]
        env:
        - name: NODE_ENV
          value: "development"
        - name: VITE_API_URL
          value: "http://your-api-url:3001"
        ports:
        - containerPort: 3000  # Vite dev server port
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5